name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel (production)
        run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_5EpHHjcqKTJgMJvAArBLjJtw
          VERCEL_PROJECT_ID: prj_BCZW3Esw6sceBfbFumNIBuWWgl1b
